# Generated by Django 5.2.5 on 2025-09-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyinglist', '0002_item_user_created_at_user_email_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lists',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
