# Generated by Django 5.2.5 on 2025-09-03 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyinglist', '0003_remove_user_lists_delete_list_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='type_product',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
